name: eyecontrol
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.18
  - pip
  - openssl
  - portaudio
  - pip:
      - numpy==1.26.4
      - protobuf==4.25.3
      - attrs==23.2.0
      - requests==2.32.3
      - tqdm==4.66.5
      - opencv-python==4.9.0.80
      - mediapipe==0.10.14
      - PyQt5==5.15.9
      - vosk==0.3.45
      - sounddevice==0.4.6
      - pyaudio==0.2.13
      - pyautogui==0.9.54
      - pyperclip==1.8.2
      - mouseinfo==0.1.3
      - pyscreeze==0.1.28
      - pygetwindow==0.0.9
      - pytweening==1.2.0
      - pyrect==0.2.0
      - matplotlib==3.9.2
      - scipy==1.14.1
      - colorama==0.4.6
      - typing-extensions==4.12.2
      - certifi==2025.7.1
      - charset_normalizer==3.3.2
      - idna==3.7
      - urllib3==2.2.3
